### ISSUE TITLE
관리자페이지 기획페이지

### ISSUE THREAD

**Issue by jongjin23** [study221007/study#1]
관리자페이지 기획페이지입니다.
편집하는부분을 공유하려고 했는데 각자 계정을적어 초대해야하는 방식인거같아
뷰페이지로 공유하겠습니다.
페이지별로 메모를 간단히 적어뒀으니 왼쪽밑에서 메모표시 체크 후 확인하시면 될것같습니다.
[관리자페이지](https://ovenapp.io/view/vqaeOqFSOI97CoAfh9xTgfz4tB3Lh1ta/)

**Comment by mskwon25** [comment]
@jongjin23 // cc. @tkddnjs 
관리자 페이지 작성해준 화면을 보면 관리자가 접속하는 사이트랑 일반 유저가 접속하는 사이트가 동일하다는 가정으로 진행된건가요?
운영자용 사이트와 일반 유저용 사이트를 별도로 생성하는것이랑 장단점 비교를 좀 해봤으면 좋겠습니다.

**Comment by jongjin23** [comment]
분리를 생각하긴 했었는데 장단점 비교후에 공유하겠습니다

**Comment by mskwon25** [comment]
@tkddnjs 상원님도 아이디어 있으면 좀 주세요 :)

**Comment by tkddnjs** [comment]
저는 동일한 사이트에서 관리자 계정과 일반 계정의 권한을 다르게 부여하는 방향으로 생각하고 있었는데 별도로 사이트 생성하는 쪽은 생각을 안해봐서 어떤 장단점이 있는지 한번 생각해보겠습니다..

**Comment by mskwon25** [comment]
@jongjin23 @tkddnjs 
보안 관점에서`일반 고객`와 `관리자`를 동일한 `User`로 처리하는 경우 아래와 같은 문제가 발생할 수 있을 것 같습니다.

* User 의 타입으로 **관리자**와 **일반 고객**을 구분한다면, 해당 값이 변경 되는 경우 **일반 고객**이 **관리자**의 기능을 접근할 수 있음
* **관리자와** **일반 고객**이 사용하게될 기능이 명확하게 구분이 되기 떄문에 하나로 처리하는 경우 모든 기능을 개발할 때 User의 타입을 체크하는 번거로움이 있을 수 있을듯
* 위와 연결되는 문제로 관리자 혹은 일반 유저의 구현에 대한 확장성이 떨어짐
  * 만약 본인 인증으로 1명당 1개의 ID를 만들 수 있다면 관리자 계정을 보유한 경우 일반 회원 가입 불가? 
  * 관리자 계정은 특정 IP 대역에서만 접근할 수 있게 설정하는 기능이 필요하다면, 어떻게 구현할 것인지?
  * 회원에 대한 여러가지 정책들을 동일하게 관리자에 적용할 것인지?
