### ISSUE TITLE
관리자페이지 기획

### ISSUE THREAD

**Issue by jongjin23** [study221007/study#6]
관리자페이지 게임관리입니다.
신경쓴다고 쓴건데 혹시 필체가 알아보기 힘드시면 코멘트 남겨주세요,,,

[1.게임관리.pdf](https://github.com/study221007/study/files/9825027/1.pdf)

**Comment by mskwon25** [comment]
#8 여기서 한번에 묶어서 처리하기 때문에 해당 이슈는 닫겠습니다 :)
