### ISSUE TITLE
관리자페이지 기획 1.1.0

### ISSUE THREAD

**Issue by jongjin23** [study221007/study#8]
관리자페이지
게임, 회원, 매출관리 페이지입니다
[관리자페이지_1.1.0.pdf](https://github.com/study221007/study/files/9872733/_1.1.0.pdf)

**Comment by tkddnjs** [comment]
올려주신 내용 중 궁금한 부분이 있어 문의드립니다..
***

*  경기리스트 화면
    * 리스트 조회 시
        * 경기시간은 표시가 안되는 이유가 있는지
        * 정렬방법을 변경할수는 없는지
    * 게임명으로 검색 시
        * 입력란에 '팀명:팀명' 이런 양식으로 입력해야하는 지
        * 입력란에 '팀명'만 입력하면 '@@:팀명', '팀명:@@' 이렇게 전부 조회가 되는지

*  경기상세보기 화면에서 
    * 경기삭제추가라고 되어있는데 경기취소와 다른 기능인지

* 회원상세정보 화면에서
    * 회원상태가 셀렉트박스로 되어있는데 회원상태를 아무때나 수정가능한 것인지

* 상품별 매출조회 화면에서
    *  검색버튼이 2개로 나눠야할 이유가 있는지
    *  리스트는 경기일자 순으로 정렬하면 어떨까요?

**Comment by jongjin23** [comment]
@tkddnjs 문의 답변입니다
***
* 경기리스트 화면
    - 경기시간은 표시가 안되는 이유가 있는지
        + 경기시간은 실수로 빼먹었습니다. 추가하겠습니다.
    - 정렬방법을 변경할수는 없는지
        + 정렬은 최신경기가 위로 올라오게만 생각했습니다. 필터가 있어 그 외에는 별도로 필요하지 않을 것 같습니다.
    - 게임명으로 검색 시
        + 키워드가 포함된 경기는 모두 검색이 됩니다.

* 경기상세보기 화면에서
    - 경기삭제추가라고 되어있는데 경기취소와 다른 기능인지
        + 경기취소는 말그대로 경기가 취소되어 무효처리가 되었을 때 사용하는 기능이고, 경기삭제는 오류가 나거나 업로드를 잘못하는 등의 이유로 리스트에서 아예 삭제를 하는 것입니다.

* 회원상세정보 화면에서
    - 회원상태가 셀렉트박스로 되어있는데 회원상태를 아무때나 수정가능한 것인지
        + 네 관리자페이지 회원정보에서 회원정보를 수정할 수 있게 하려고 합니다.

* 상품별 매출조회 화면에서
    - 검색버튼이 2개로 나눠야할 이유가 있는지
        + 셀렉트박스 지정과 검색텍스트를 모두 입력 후 검색을 했을 때 혼동을 주지 않기 위해서 별도로 버튼을 부여했습니다.
    - 리스트는 경기일자 순으로 정렬하면 어떨까요?
        + 같은 게임명으로 여러 경기가 이루어 질 수 있고, 동시간대 경기가 이루어지는 경우도 빈번합니다. 세부내역에서는 경기일자 순으로 정렬을 하고, 조회화면에서는 가나다순이나 총 매출 순으로 정렬을 하는게 좋을 것 같습니다.

**Comment by tkddnjs** [comment]
우선 경기리스트 및 경기 등록화면 기획서 작성하여 업로드합니다.

바로 이어서 경기 상세화면 작성해서 업로드하겠습니다.

[경기관리 기획서.pdf](https://github.com/study221007/study/files/9886515/default.pdf)

**Comment by tkddnjs** [comment]
경기관리 기획서 내용 추가하여 업로드합니다.

[경기관리 기획서_1.1.0.pdf](https://github.com/study221007/study/files/9887505/_1.1.0.pdf)

**Comment by jongjin23** [comment]
@tkddnjs 
기획서 내용중 궁금한내용과 의견들입니다
* * *
1. 경기리스트
    - 경기 진행상태에서 삭제는 리스트(DB)에서 완전히 삭제하는 걸 생각했었습니다. 진행상태 중 하나로 생각하는게 나을까요?
    - 셀렉트박스 지정 시 바로 검색이 되나요?
    - 게임명 검색시에 홈팀과 원정팀을 모두 지정해서 검색할 수 있으면 좋을 것 같습니다. 특수문자 중 ":"는 허용하는게 어떨까요?
    - 경기일자 검색에서 월단위나 연단위 검색도 가능한가요?
    - 페이지당 표시 갯수와 스크롤이 함께있는건 기능이 퇴색된다고 생각하는데 그 부분에 대해서는 혹시 어떻게 생각하시나요?

2. 게임등록
    - 경기 등록 시 보통 최소 3일 이후의 경기를 미리 등록하는것일텐데 기본값이 현재로 되어있으면 오히려 불편하지 않을까요?
    - 리그는 꼭 정해진 리그 중에서만 선택가능한가요? 국가대표전 등이나 리그 외 경기도 등록할 수 있는방법은 없을까요?
    - 리그별 팀 리스트를 셀렉트박스로 하시는건 DB에 테이블을 별도로 관리하는건가요?
    - 경기방식 두가지를 동시에 등록(체크박스를 둘 다 선택)해도 되지 않을까요?

3. 경기상세보기
    - 한 유저가 같은 경기를 중복구매하는 경우도 있을 것 같은데 구매유저가 아닌 판매량 등으로 표시하는건 어떨까요?

4. 경기결과등록
    - 점수와 별개로 몰수패 등의 상황이 생기는 경우도 있을 것 같습니다. 승부차기 등은 어짜피 기록식에 영향을 미치지 않을 것 같은데, 승무패를 지정해서 등록하고 코멘트 기록칸을 만들면 어떨까요?

**Comment by jongjin23** [comment]
로그인, 메인페이지, 회원관리화면 입니다.
[관리자페이지_2.1.0](https://github.com/study221007/study/files/9896800/_2.1.0.pdf)

**Comment by tkddnjs** [comment]
문의 주신 부분 답변 및 기획서 수정본 업로드 합니다.
***

> 경기 진행상태에서 삭제는 리스트(DB)에서 완전히 삭제하는 걸 생각했었습니다. 진행상태 중 하나로 생각하는게 나을까요?
* 실수로 삭제해서 바로 복구해야하는 경우가 있을 것 같아 DB에 임시로 저장해두고 삭제대기 상태(일정 시간이 지나면 삭제)로 두면 어떨까 싶습니다.

> 리그는 꼭 정해진 리그 중에서만 선택가능한가요? 국가대표전 등이나 리그 외 경기도 등록할 수 있는방법은 없을까요?
* 우선은 정해진 리그에서만 선택가능하게 하려고 합니다.

> 리그별 팀 리스트를 셀렉트박스로 하시는건 DB에 테이블을 별도로 관리하는건가요?
* 네, 팀 테이블을 별도로 두고 관리하려고 합니다.


[경기관리 기획서_1.1.1.pdf](https://github.com/study221007/study/files/9898723/_1.1.1.pdf)

그 외에 의견주신 부분은 수정본에 반영하였습니다.

**Comment by tkddnjs** [comment]
관리자 페이지 기획을 기능단위로 #9, #10  로 나눠서 처리하기 때문에 해당 이슈를 닫습니다.
